/**
 * Seeded Chennai demo dataset (section 41/59) — shape-identical to real API
 * responses so DEMO_MODE=true can drive the whole app with zero backend.
 * Mirrors backend/api/scripts/seed.py's Chennai hazards for consistency
 * between a live-backend demo and an offline one.
 */
import type { AppNotification, Hazard, HomeResponse, ReportListItem } from '@/types';

export const DEMO_CITY = 'Chennai';
export const DEMO_USER_NAME = 'Arun';

const now = () => new Date().toISOString();
const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const DEMO_HAZARDS: Hazard[] = [
  {
    id: 'demo-pth-1029',
    type: 'POTHOLE',
    latitude: 12.9784,
    longitude: 80.2205,
    locationText: 'Velachery Main Road, near MRTS Station',
    roadName: 'Velachery Main Road',
    severity: 'HIGH',
    status: 'ACTIVE',
    aiConfidence: 0.94,
    imageUrl: null,
    description: 'Pothole cluster reported on Velachery Main Road.',
    distanceMeters: 800,
    verificationNote: 'Recently verified by SafePath road observations.',
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(15),
    lastObservedAt: minutesAgo(15),
  },
  {
    id: 'demo-pth-1030',
    type: 'FLOODING',
    latitude: 12.901,
    longitude: 80.2279,
    locationText: 'OMR Toll Plaza, Sholinganallur',
    roadName: 'OMR',
    severity: 'MEDIUM',
    status: 'VERIFIED',
    aiConfidence: 0.87,
    imageUrl: null,
    description: 'Waterlogging near the toll plaza.',
    distanceMeters: 2100,
    verificationNote: 'Confirmed by multiple recent road observations.',
    createdAt: minutesAgo(200),
    updatedAt: minutesAgo(40),
    lastObservedAt: minutesAgo(40),
  },
  {
    id: 'demo-pth-1031',
    type: 'POTHOLE',
    latitude: 13.01,
    longitude: 80.2121,
    locationText: 'GST Road, near Guindy Industrial Estate',
    roadName: 'GST Road',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.96,
    imageUrl: null,
    description: 'Deep pothole cluster reported on GST Road.',
    distanceMeters: 3400,
    verificationNote: 'Recently verified by SafePath road observations.',
    createdAt: minutesAgo(60),
    updatedAt: minutesAgo(5),
    lastObservedAt: minutesAgo(5),
  },
  {
    id: 'demo-pth-1032',
    type: 'ROAD_DAMAGE',
    latitude: 13.0604,
    longitude: 80.2496,
    locationText: 'Anna Salai, near Gemini Flyover',
    roadName: 'Anna Salai',
    severity: 'HIGH',
    status: 'UNDER_REVIEW',
    aiConfidence: 0.91,
    imageUrl: null,
    description: 'Road surface damage near Gemini Flyover.',
    distanceMeters: 5200,
    verificationNote: null,
    createdAt: minutesAgo(30),
    updatedAt: minutesAgo(30),
    lastObservedAt: minutesAgo(30),
  },
  {
    id: 'demo-pth-1033',
    type: 'POTHOLE',
    latitude: 12.9829,
    longitude: 80.2594,
    locationText: 'East Coast Road, near Thiruvanmiyur Junction',
    roadName: 'East Coast Road (ECR)',
    severity: 'MEDIUM',
    status: 'REPORTED',
    aiConfidence: 0.88,
    imageUrl: null,
    description: 'Asphalt erosion and pothole on outer lane.',
    distanceMeters: 1400,
    verificationNote: 'Citizen reported via mobile app.',
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(90),
    lastObservedAt: minutesAgo(90),
  },
  {
    id: 'demo-pth-1034',
    type: 'DEBRIS',
    latitude: 13.0569,
    longitude: 80.2508,
    locationText: 'Mount Road, near LIC Building',
    roadName: 'Mount Road',
    severity: 'LOW',
    status: 'UNDER_REPAIR',
    aiConfidence: 0.82,
    imageUrl: null,
    description: 'Construction debris spilling onto left bus lane.',
    distanceMeters: 2800,
    verificationNote: 'Work order assigned to GCC maintenance team.',
    createdAt: minutesAgo(300),
    updatedAt: minutesAgo(60),
    lastObservedAt: minutesAgo(60),
  },
  {
    id: 'demo-pth-1035',
    type: 'BROKEN_PAVEMENT',
    latitude: 13.0418,
    longitude: 80.2341,
    locationText: 'Pondy Bazaar, T. Nagar',
    roadName: 'Pondy Bazaar Road',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    aiConfidence: 0.89,
    imageUrl: null,
    description: 'Broken pavement tiles and exposed curb edge.',
    distanceMeters: 1900,
    verificationNote: 'AI camera automated detection.',
    createdAt: minutesAgo(180),
    updatedAt: minutesAgo(20),
    lastObservedAt: minutesAgo(20),
  },
  {
    id: 'demo-pth-1036',
    type: 'POTHOLE',
    latitude: 13.0827,
    longitude: 80.2437,
    locationText: 'Poonamallee High Road, Kilpauk',
    roadName: 'Poonamallee High Road',
    severity: 'HIGH',
    status: 'RESOLVED',
    aiConfidence: 0.95,
    imageUrl: null,
    description: 'Severe pothole repaired by emergency cold mix.',
    distanceMeters: 4100,
    verificationNote: 'Verified resolved by Municipal Inspector.',
    createdAt: minutesAgo(1440),
    updatedAt: minutesAgo(120),
    lastObservedAt: minutesAgo(120),
  },
  {
    id: 'demo-pth-1037',
    type: 'BROKEN_PAVEMENT',
    latitude: 13.0336,
    longitude: 80.2678,
    locationText: 'Luz Church Road, Mylapore',
    roadName: 'Luz Church Road',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.97,
    imageUrl: null,
    description: 'Uncovered storm drain opening near bus stop.',
    distanceMeters: 1200,
    verificationNote: 'High safety risk — barricaded temporarily.',
    createdAt: minutesAgo(45),
    updatedAt: minutesAgo(10),
    lastObservedAt: minutesAgo(10),
  },
  {
    id: 'demo-pth-1038',
    type: 'ROAD_DAMAGE',
    latitude: 13.0067,
    longitude: 80.2571,
    locationText: 'Lattice Bridge Road, Adyar',
    roadName: 'LB Road',
    severity: 'HIGH',
    status: 'VERIFIED',
    aiConfidence: 0.92,
    imageUrl: null,
    description: 'Sunken road section causing traffic slowing.',
    distanceMeters: 2300,
    verificationNote: 'Verified by fleet sensor observation.',
    createdAt: minutesAgo(240),
    updatedAt: minutesAgo(30),
    lastObservedAt: minutesAgo(30),
  },
  {
    id: 'demo-pth-1039',
    type: 'FLOODING',
    latitude: 13.0722,
    longitude: 80.2394,
    locationText: 'Sterling Road Subway, Nungambakkam',
    roadName: 'Sterling Road',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.96,
    imageUrl: null,
    description: 'Monsoon runoff accumulation in subway corridor.',
    distanceMeters: 3800,
    verificationNote: 'Pumping squad dispatched.',
    createdAt: minutesAgo(50),
    updatedAt: minutesAgo(5),
    lastObservedAt: minutesAgo(5),
  },
  {
    id: 'demo-pth-1040',
    type: 'POTHOLE',
    latitude: 13.0694,
    longitude: 80.1948,
    locationText: '100 Feet Road, Koyambedu',
    roadName: '100 Feet Road',
    severity: 'HIGH',
    status: 'UNDER_REVIEW',
    aiConfidence: 0.90,
    imageUrl: null,
    description: 'Deep rutted asphalt on heavy commercial truck lane.',
    distanceMeters: 4900,
    verificationNote: null,
    createdAt: minutesAgo(110),
    updatedAt: minutesAgo(25),
    lastObservedAt: minutesAgo(25),
  },
];

export const DEMO_HOME: HomeResponse = {
  greeting: 'Good Morning',
  userName: DEMO_USER_NAME,
  cityName: DEMO_CITY,
  stats: { nearbyCount: 24, criticalCount: 6, warningCount: 18 },
  nearbyHazards: DEMO_HAZARDS,
  mapMarkers: DEMO_HAZARDS,
};

export const DEMO_REPORTS: ReportListItem[] = [
  {
    id: 'demo-report-1',
    reportCode: 'PTH-1042',
    hazardType: 'POTHOLE',
    severity: 'HIGH',
    status: 'UNDER_REVIEW',
    locationText: 'Velachery Main Road, Chennai',
    createdAt: minutesAgo(600),
  },
  {
    id: 'demo-report-2',
    reportCode: 'FLD-2089',
    hazardType: 'FLOODING',
    severity: 'CRITICAL',
    status: 'VERIFIED',
    locationText: 'Sterling Road Subway, Nungambakkam',
    createdAt: minutesAgo(320),
  },
  {
    id: 'demo-report-3',
    reportCode: 'MNV-5012',
    hazardType: 'BROKEN_PAVEMENT',
    severity: 'CRITICAL',
    status: 'UNDER_REPAIR',
    locationText: 'Luz Church Road, Mylapore',
    createdAt: minutesAgo(180),
  },
  {
    id: 'demo-report-4',
    reportCode: 'DMG-3051',
    hazardType: 'ROAD_DAMAGE',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    locationText: 'Lattice Bridge Road, Adyar, Chennai',
    createdAt: minutesAgo(1440),
  },
  {
    id: 'demo-report-5',
    reportCode: 'PTH-4102',
    hazardType: 'POTHOLE',
    severity: 'HIGH',
    status: 'RESOLVED',
    locationText: 'Poonamallee High Road, Kilpauk',
    createdAt: minutesAgo(2880),
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'demo-notif-1',
    type: 'CRITICAL_HAZARD',
    title: 'Critical hazard nearby',
    body: 'A critical pothole was detected 300m ahead on GST Road.',
    isRead: false,
    relatedHazardId: 'demo-pth-1031',
    relatedReportId: null,
    createdAt: minutesAgo(10),
  },
  {
    id: 'demo-notif-2',
    type: 'REPORT_UPDATE',
    title: 'Your report has been verified',
    body: 'Report FLD-2089 (Sterling Road Subway) has been verified by Municipality Officers.',
    isRead: false,
    relatedHazardId: null,
    relatedReportId: 'demo-report-2',
    createdAt: minutesAgo(45),
  },
  {
    id: 'demo-notif-3',
    type: 'REPORT_UPDATE',
    title: 'Road Hazard Resolved!',
    body: 'Report DMG-3051 on LB Road Adyar has been repaired by GCC Contractors.',
    isRead: false,
    relatedHazardId: 'demo-pth-1038',
    relatedReportId: 'demo-report-4',
    createdAt: minutesAgo(120),
  },
  {
    id: 'demo-notif-4',
    type: 'SYSTEM',
    title: 'Weekly Chennai Road Safety Digest',
    body: '14 road hazards were repaired across Chennai South in the last 7 days.',
    isRead: true,
    relatedHazardId: null,
    relatedReportId: null,
    createdAt: minutesAgo(720),
  },
  {
    id: 'demo-notif-5',
    type: 'SYSTEM',
    title: 'Welcome to SafePath AI',
    body: 'Thanks for helping make Chennai roads safer.',
    isRead: true,
    relatedHazardId: null,
    relatedReportId: null,
    createdAt: minutesAgo(1440),
  },
];

export { now as demoNow };
