"""municipality app schema

Revision ID: 9ed75ca12aaa
Revises: c67b0e8d2d81
Create Date: 2026-08-21 22:53:34.765020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 — model columns use geoalchemy2.types.Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ed75ca12aaa'
down_revision: Union[str, None] = 'c67b0e8d2d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_city_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['primary_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipalities_code'), 'municipalities', ['code'], unique=True)
    op.create_table('wards',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_city_id'), 'wards', ['city_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_city_id'), 'audit_logs', ['city_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_municipality_id'), 'audit_logs', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('municipality_city_access',
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipality_city_access_city_id'), 'municipality_city_access', ['city_id'], unique=False)
    op.create_index(op.f('ix_municipality_city_access_municipality_id'), 'municipality_city_access', ['municipality_id'], unique=False)
    op.create_table('municipality_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('officer_role', sa.String(length=32), nullable=False),
    sa.Column('default_city_id', sa.UUID(), nullable=True),
    sa.Column('ward_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_municipality_profiles_municipality_id'), 'municipality_profiles', ['municipality_id'], unique=False)
    op.create_table('repairs',
    sa.Column('repair_code', sa.String(length=32), nullable=False),
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_officer_name', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repairs_city_id'), 'repairs', ['city_id'], unique=False)
    op.create_index(op.f('ix_repairs_hazard_id'), 'repairs', ['hazard_id'], unique=False)
    op.create_index(op.f('ix_repairs_municipality_id'), 'repairs', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_repairs_repair_code'), 'repairs', ['repair_code'], unique=True)
    op.create_index(op.f('ix_repairs_status'), 'repairs', ['status'], unique=False)
    op.create_table('inspections',
    sa.Column('repair_id', sa.UUID(), nullable=False),
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_hazard_id'), 'inspections', ['hazard_id'], unique=False)
    op.create_index(op.f('ix_inspections_repair_id'), 'inspections', ['repair_id'], unique=False)
    op.create_table('repair_progress',
    sa.Column('repair_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_by_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_progress_repair_id'), 'repair_progress', ['repair_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('repair_id', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('evidence_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolutions_hazard_id'), 'resolutions', ['hazard_id'], unique=False)
    op.add_column('cities', sa.Column('code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_cities_code'), 'cities', ['code'], unique=False)
    op.add_column('fleet_observations', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('fleet_observations', sa.Column('road_id', sa.UUID(), nullable=True))
    op.add_column('fleet_observations', sa.Column('operator_id', sa.String(length=64), nullable=True))
    op.add_column('fleet_observations', sa.Column('observation_state', sa.String(length=16), nullable=True))
    op.add_column('fleet_observations', sa.Column('severity', sa.String(length=16), nullable=True))
    op.add_column('fleet_observations', sa.Column('image_url', sa.String(length=1024), nullable=True))
    op.add_column('fleet_observations', sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fleet_observations', sa.Column('data_quality', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_fleet_observations_road_id'), 'fleet_observations', ['road_id'], unique=False)
    op.create_foreign_key(None, 'fleet_observations', 'roads', ['road_id'], ['id'])
    op.add_column('hazards', sa.Column('hazard_code', sa.String(length=32), nullable=True))
    op.add_column('hazards', sa.Column('ward_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hazards_hazard_code'), 'hazards', ['hazard_code'], unique=True)
    op.create_index(op.f('ix_hazards_ward_id'), 'hazards', ['ward_id'], unique=False)
    op.create_foreign_key(None, 'hazards', 'wards', ['ward_id'], ['id'])
    op.add_column('municipality_actions', sa.Column('performed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('municipality_actions', sa.Column('from_status', sa.String(length=24), nullable=True))
    op.add_column('municipality_actions', sa.Column('to_status', sa.String(length=24), nullable=True))
    op.add_column('municipality_actions', sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'municipality_actions', 'users', ['performed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'municipality_actions', type_='foreignkey')
    op.drop_column('municipality_actions', 'action_metadata')
    op.drop_column('municipality_actions', 'to_status')
    op.drop_column('municipality_actions', 'from_status')
    op.drop_column('municipality_actions', 'performed_by_user_id')
    op.drop_constraint(None, 'hazards', type_='foreignkey')
    op.drop_index(op.f('ix_hazards_ward_id'), table_name='hazards')
    op.drop_index(op.f('ix_hazards_hazard_code'), table_name='hazards')
    op.drop_column('hazards', 'ward_id')
    op.drop_column('hazards', 'hazard_code')
    op.drop_constraint(None, 'fleet_observations', type_='foreignkey')
    op.drop_index(op.f('ix_fleet_observations_road_id'), table_name='fleet_observations')
    op.drop_column('fleet_observations', 'data_quality')
    op.drop_column('fleet_observations', 'bounding_box')
    op.drop_column('fleet_observations', 'image_url')
    op.drop_column('fleet_observations', 'severity')
    op.drop_column('fleet_observations', 'observation_state')
    op.drop_column('fleet_observations', 'operator_id')
    op.drop_column('fleet_observations', 'road_id')
    op.drop_column('fleet_observations', 'location')
    op.drop_index(op.f('ix_cities_code'), table_name='cities')
    op.drop_column('cities', 'code')
    op.drop_index(op.f('ix_resolutions_hazard_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_repair_progress_repair_id'), table_name='repair_progress')
    op.drop_table('repair_progress')
    op.drop_index(op.f('ix_inspections_repair_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_hazard_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_repairs_status'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_repair_code'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_municipality_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_hazard_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_city_id'), table_name='repairs')
    op.drop_table('repairs')
    op.drop_index(op.f('ix_municipality_profiles_municipality_id'), table_name='municipality_profiles')
    op.drop_table('municipality_profiles')
    op.drop_index(op.f('ix_municipality_city_access_municipality_id'), table_name='municipality_city_access')
    op.drop_index(op.f('ix_municipality_city_access_city_id'), table_name='municipality_city_access')
    op.drop_table('municipality_city_access')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_municipality_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_city_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wards_city_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_municipalities_code'), table_name='municipalities')
    op.drop_table('municipalities')
    # ### end Alembic commands ###
