import type {
  AnalyticsSummary,
  City,
  Dashboard,
  MunicipalityHazard,
  MunicipalityHazardDetail,
  MunicipalityMeResponse,
  MunicipalityOfficer,
  Repair,
  RepairDetail,
} from '@/types/municipality';

export const DEMO_OFFICER: MunicipalityOfficer = {
  id: '467ce1f8-a836-4fc7-b0f4-24af089cef6c',
  fullName: 'Priya Raghavan',
  email: 'officer@chennai.gov.in',
  role: 'MUNICIPALITY_OFFICER',
  officerRole: 'MUNICIPALITY_OFFICER',
  municipalityId: '1d61a6d0-9b8e-4180-ad60-4a986aaa3c4a',
  municipalityCode: 'MUN-CHN',
  municipalityName: 'Greater Chennai Corporation',
  allowedCityIds: ['59fd1a9b-7f0e-4090-82ea-5372a471af10'],
  defaultCityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
  wardIds: ['w-1', 'w-2', 'w-3', 'w-4', 'w-5', 'w-6'],
  permissions: ['VIEW_HAZARDS', 'ASSIGN_REPAIR', 'UPDATE_REPAIR', 'INSPECT_HAZARD', 'RESOLVE_HAZARD', 'VIEW_ANALYTICS'],
};

export const DEMO_CITIES: City[] = [
  {
    id: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    code: 'CHN',
    name: 'Chennai',
    state: 'Tamil Nadu',
    centerLatitude: 13.0827,
    centerLongitude: 80.2707,
    wardCount: 6,
  },
  {
    id: 'cbe-city-id',
    code: 'CBE',
    name: 'Coimbatore',
    state: 'Tamil Nadu',
    centerLatitude: 11.0168,
    centerLongitude: 76.9558,
    wardCount: 4,
  },
];

export const DEMO_ME_RESPONSE: MunicipalityMeResponse = {
  officer: DEMO_OFFICER,
  authorizedCities: DEMO_CITIES,
};

export const DEMO_DASHBOARD: Dashboard = {
  cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
  cityName: 'Chennai',
  activeHazards: 16,
  criticalHazards: 4,
  underRepair: 3,
  resolvedToday: 5,
  priorityRoads: [
    {
      roadName: 'Velachery Main Road',
      priority: 'CRITICAL',
      activeHazardCount: 3,
      criticalHazardCount: 2,
      reason: 'Multiple deep potholes on active bus route',
    },
    {
      roadName: 'GST Road',
      priority: 'HIGH',
      activeHazardCount: 4,
      criticalHazardCount: 1,
      reason: 'Corridor underpass surface deterioration',
    },
  ],
  recentActivity: [
    {
      id: 'act-1',
      label: 'PTH-1029 verified by 5 fleet observations',
      detail: 'Confidence score 94%',
      hazardId: 'pth-1029',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'act-2',
      label: 'Repair REP-201 assigned to Metro Roadways',
      detail: 'Target date: 24h',
      hazardId: 'pth-1029',
      createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
  ],
  fleetCoverage: {
    observedTodayKmEstimate: 142.5,
    coveragePercent: 88,
    dataGapSegments: 3,
  },
  generatedAt: new Date().toISOString(),
};

export const DEMO_HAZARDS: MunicipalityHazard[] = [
  {
    id: 'pth-1029',
    hazardCode: 'PTH-1029',
    type: 'POTHOLE',
    latitude: 12.9815,
    longitude: 80.218,
    locationText: 'Velachery Main Road, Near Vijaya Nagar Bus Stand',
    roadName: 'Velachery Main Road',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-2',
    wardName: 'Ward 2 - Velachery',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    description: 'Deep pothole on left lane near bus bay.',
    sourceSummary: 'Citizen report + 5 Fleet observations',
    repairStatus: 'ASSIGNED',
    repairCode: 'REP-201',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'pth-1030',
    hazardCode: 'PTH-1030',
    type: 'POTHOLE',
    latitude: 13.0067,
    longitude: 80.2023,
    locationText: 'GST Road, Guindy Flyover Underpass',
    roadName: 'GST Road',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-4',
    wardName: 'Ward 4 - Guindy',
    severity: 'HIGH',
    status: 'ACTIVE',
    aiConfidence: 0.82,
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    description: 'Pothole developing under flyover shadow.',
    sourceSummary: 'AI Detection (Fleet)',
    repairStatus: null,
    repairCode: null,
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'pth-1031',
    hazardCode: 'PTH-1031',
    type: 'POTHOLE',
    latitude: 12.901,
    longitude: 80.2279,
    locationText: 'OMR, Sholinganallur Junction',
    roadName: 'OMR',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-6',
    wardName: 'Ward 6 - Sholinganallur',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    aiConfidence: 0.88,
    imageUrl: 'https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?w=600&auto=format&fit=crop&q=80',
    description: 'Road surface crack spreading across right lane.',
    sourceSummary: '4 Fleet observations',
    repairStatus: 'IN_PROGRESS',
    repairCode: 'REP-202',
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
  },
];

export const DEMO_HAZARD_DETAIL: MunicipalityHazardDetail = {
  ...DEMO_HAZARDS[0],
  citizenReports: [
    {
      id: 'cr-1',
      reportCode: 'REP-CHN-101',
      hazardType: 'POTHOLE',
      severity: 'CRITICAL',
      description: 'Dangerous pothole, multiple two-wheelers skidding.',
      media: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80'],
      createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    },
  ],
  latestAiAnalysis: {
    id: 'ai-1',
    detected: true,
    confidence: 0.94,
    severity: 'CRITICAL',
    modelVersion: 'SafePath-YOLOv8-v2.1',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  latestFleetObservations: [
    {
      id: 'fo-1',
      vehicleId: 'BUS-TN-01-N-9988',
      observedAt: new Date(Date.now() - 3600000).toISOString(),
      observationState: 'CONFIRMED',
      confidence: 0.94,
      severity: 'CRITICAL',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
      latitude: 12.9815,
      longitude: 80.218,
      dataQuality: 'HIGH',
    },
  ],
  municipalityActions: [
    {
      id: 'act-1',
      actionType: 'ASSIGN_REPAIR',
      notes: 'Assigned to Chennai Metro Roadways Corp with 24h SLA',
      performedBy: 'Priya Raghavan',
      fromStatus: 'ACTIVE',
      toStatus: 'ACTIVE',
      createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
  ],
  currentRepair: {
    id: 'rep-201',
    repairCode: 'REP-201',
    status: 'ASSIGNED',
    priority: 'HIGH',
    team: 'Chennai Metro Roadways Corp',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
  },
  priority: {
    label: 'CRITICAL',
    score: 92,
    reasons: ['High bus traffic route', 'Deep pothole (>12cm)', 'Multiple vehicle strikes detected'],
    recommendation: 'Immediate cold-mix asphalt patch required within 24 hours.',
  },
  resolutionState: 'ACTIVE',
  reopenedFromHazardId: null,
};

export const DEMO_REPAIRS: Repair[] = [
  {
    id: 'rep-201',
    repairCode: 'REP-201',
    hazardId: 'pth-1029',
    hazardRoadName: 'Velachery Main Road',
    hazardLocationText: 'Velachery Main Road, Near Vijaya Nagar Bus Stand',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    department: 'Roads & Bridges',
    zone: 'South Zone',
    team: 'Chennai Metro Roadways Corp',
    assignedOfficerName: 'Priya Raghavan',
    priority: 'HIGH',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
    status: 'ASSIGNED',
    notes: 'Urgent patch requested by Ward 2 supervisor.',
    startedAt: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'rep-202',
    repairCode: 'REP-202',
    hazardId: 'pth-1031',
    hazardRoadName: 'OMR',
    hazardLocationText: 'OMR, Sholinganallur Junction',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    department: 'Highways Dept',
    zone: 'East Zone',
    team: 'Coromandel Infrastructure Ltd',
    assignedOfficerName: 'Priya Raghavan',
    priority: 'MEDIUM',
    targetDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: 'IN_PROGRESS',
    notes: 'Surface crack sealing in progress.',
    startedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
  },
];

export const DEMO_REPAIR_DETAIL: RepairDetail = {
  ...DEMO_REPAIRS[0],
  progressEntries: [],
  timeline: [
    {
      id: 'tl-1',
      label: 'Repair Created & Assigned',
      detail: 'Assigned to Chennai Metro Roadways Corp',
      fromStatus: null,
      toStatus: 'ASSIGNED',
      actor: 'Priya Raghavan',
      createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
  ],
};

export const DEMO_ANALYTICS_SUMMARY: AnalyticsSummary = {
  activeHazards: 16,
  criticalHazards: 4,
  resolvedThisWeek: 12,
  avgResolutionTimeHours: 42.5,
  recurringHazardRoads: 2,
  citizenReportsCount: 28,
  fleetObservationCount: 95,
  avgRepairTurnaroundHours: 36.0,
};
