import type {
  AnalyticsSummary,
  City,
  Dashboard,
  MunicipalityHazard,
  MunicipalityHazardDetail,
  MunicipalityMeResponse,
  MunicipalityOfficer,
  Repair,
  RepairDetail,
} from '@/types/municipality';

export const DEMO_OFFICER: MunicipalityOfficer = {
  id: '467ce1f8-a836-4fc7-b0f4-24af089cef6c',
  fullName: 'Officer Rajesh Kumar',
  email: 'rajesh.kumar@bbmp.gov.in',
  role: 'MUNICIPALITY_OFFICER',
  officerRole: 'MUNICIPALITY_OFFICER',
  municipalityId: '1d61a6d0-9b8e-4180-ad60-4a986aaa3c4a',
  municipalityCode: 'BBMP-01',
  municipalityName: 'Bruhat Bengaluru Mahanagara Palike (BBMP)',
  allowedCityIds: ['59fd1a9b-7f0e-4090-82ea-5372a471af10', 'c_chn', 'c_hyd', 'c_mum', 'c_del'],
  defaultCityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
  wardIds: ['w-1', 'w-2', 'w-3', 'w-4', 'w-5', 'w-6', 'w-7', 'w-8'],
  permissions: ['VIEW_HAZARDS', 'ASSIGN_REPAIR', 'UPDATE_REPAIR', 'INSPECT_HAZARD', 'RESOLVE_HAZARD', 'VIEW_ANALYTICS'],
};

export const DEMO_CITIES: City[] = [
  {
    id: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    code: 'BLR',
    name: 'Bengaluru',
    state: 'Karnataka',
    centerLatitude: 12.9716,
    centerLongitude: 77.5946,
    wardCount: 198,
  },
  {
    id: 'c_chn',
    code: 'CHN',
    name: 'Chennai',
    state: 'Tamil Nadu',
    centerLatitude: 13.0827,
    centerLongitude: 80.2707,
    wardCount: 200,
  },
  {
    id: 'c_hyd',
    code: 'HYD',
    name: 'Hyderabad',
    state: 'Telangana',
    centerLatitude: 17.385,
    centerLongitude: 78.4867,
    wardCount: 150,
  },
  {
    id: 'c_mum',
    code: 'MUM',
    name: 'Mumbai',
    state: 'Maharashtra',
    centerLatitude: 19.076,
    centerLongitude: 72.8777,
    wardCount: 227,
  },
  {
    id: 'c_del',
    code: 'DEL',
    name: 'Delhi NCR',
    state: 'Delhi',
    centerLatitude: 28.6139,
    centerLongitude: 77.209,
    wardCount: 250,
  },
];

export const DEMO_ME_RESPONSE: MunicipalityMeResponse = {
  officer: DEMO_OFFICER,
  authorizedCities: DEMO_CITIES,
};

export const DEMO_DASHBOARD: Dashboard = {
  cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
  cityName: 'Bengaluru Metro Zone',
  activeHazards: 42,
  criticalHazards: 8,
  underRepair: 12,
  resolvedToday: 18,
  priorityRoads: [
    {
      roadName: '100 Feet Road, Indiranagar',
      priority: 'CRITICAL',
      activeHazardCount: 5,
      criticalHazardCount: 3,
      reason: 'Deep pothole cluster on heavy traffic commercial corridor',
    },
    {
      roadName: 'Outer Ring Road, Marathahalli',
      priority: 'CRITICAL',
      activeHazardCount: 4,
      criticalHazardCount: 2,
      reason: 'Underpass waterlogging & asphalt erosion',
    },
    {
      roadName: 'Velachery Main Road, Chennai',
      priority: 'HIGH',
      activeHazardCount: 4,
      criticalHazardCount: 1,
      reason: 'Multiple deep potholes on active bus route',
    },
    {
      roadName: 'Bannerghatta Road, Bengaluru',
      priority: 'HIGH',
      activeHazardCount: 3,
      criticalHazardCount: 1,
      reason: 'Metro construction zone carriageway damage',
    },
  ],
  recentActivity: [
    {
      id: 'act-1',
      label: 'PTH-BLR-1002 verified by 8 fleet dash-cam observations',
      detail: 'YOLO26n confidence score 96%',
      hazardId: 'pth-1002',
      createdAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: 'act-2',
      label: 'Work Order REP-301 assigned to BBMP Road Infra Division',
      detail: 'SLA Target: 24 Hours',
      hazardId: 'pth-1002',
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: 'act-3',
      label: 'Citizen Report RPT-BLR-401 verified by AI Model',
      detail: 'Ward 101 Indiranagar',
      hazardId: 'pth-1001',
      createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    {
      id: 'act-4',
      label: 'Repair REP-208 marked Ready for Inspection',
      detail: 'Coromandel Infrastructure Ltd',
      hazardId: 'pth-1004',
      createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    },
  ],
  fleetCoverage: {
    observedTodayKmEstimate: 342.8,
    coveragePercent: 92,
    dataGapSegments: 4,
  },
  generatedAt: new Date().toISOString(),
};

export const DEMO_HAZARDS: MunicipalityHazard[] = [
  {
    id: 'pth-1001',
    hazardCode: 'PTH-BLR-1001',
    type: 'POTHOLE',
    latitude: 12.9784,
    longitude: 77.6408,
    locationText: '100 Feet Road, Near HAL 2nd Stage Junction, Indiranagar',
    roadName: '100 Feet Road, Indiranagar',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-101',
    wardName: 'Ward 101 - Indiranagar',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    description: 'Severe 14cm deep pothole near traffic signal causing vehicle slowdowns.',
    sourceSummary: 'Citizen Report + 8 Fleet Observations',
    repairStatus: 'ASSIGNED',
    repairCode: 'REP-301',
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    lastObservedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'pth-1002',
    hazardCode: 'PTH-BLR-1002',
    type: 'POTHOLE',
    latitude: 12.9569,
    longitude: 77.7011,
    locationText: 'Outer Ring Road, Near Marathahalli Bridge Bus Stop',
    roadName: 'Outer Ring Road',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-103',
    wardName: 'Ward 103 - Marathahalli',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    description: 'Pothole cluster under flyover causing monsoon water accumulation.',
    sourceSummary: 'AI Detection (Fleet Dash-cam)',
    repairStatus: 'IN_PROGRESS',
    repairCode: 'REP-302',
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'pth-1003',
    hazardCode: 'PTH-BLR-1003',
    type: 'ROAD_DAMAGE',
    latitude: 12.9352,
    longitude: 77.6245,
    locationText: '80 Feet Road, 4th Block Koramangala',
    roadName: '80 Feet Road Koramangala',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-102',
    wardName: 'Ward 102 - Koramangala',
    severity: 'HIGH',
    status: 'ACTIVE',
    aiConfidence: 0.89,
    imageUrl: 'https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?w=600&auto=format&fit=crop&q=80',
    description: 'Asphalt crumbling along 25m stretch on right carriageway.',
    sourceSummary: '6 Fleet Observations',
    repairStatus: 'READY_FOR_INSPECTION',
    repairCode: 'REP-303',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'pth-1004',
    hazardCode: 'PTH-BLR-1004',
    type: 'FLOODING',
    latitude: 12.8981,
    longitude: 77.5982,
    locationText: 'Bannerghatta Road, Near IIM Bangalore',
    roadName: 'Bannerghatta Main Road',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    wardId: 'w-105',
    wardName: 'Ward 105 - Arekere',
    severity: 'HIGH',
    status: 'ACTIVE',
    aiConfidence: 0.91,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    description: 'Waterlogging & submerged potholes near metro construction gate.',
    sourceSummary: 'Citizen Report + 4 Fleet Observations',
    repairStatus: 'ASSIGNED',
    repairCode: 'REP-304',
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'pth-1029',
    hazardCode: 'PTH-CHN-1029',
    type: 'POTHOLE',
    latitude: 12.9815,
    longitude: 80.218,
    locationText: 'Velachery Main Road, Near Vijaya Nagar Bus Stand, Chennai',
    roadName: 'Velachery Main Road',
    cityId: 'c_chn',
    wardId: 'w-2',
    wardName: 'Ward 2 - Velachery',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    description: 'Deep pothole on left lane near bus bay.',
    sourceSummary: 'Citizen report + 5 Fleet observations',
    repairStatus: 'ASSIGNED',
    repairCode: 'REP-201',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'pth-1030',
    hazardCode: 'PTH-CHN-1030',
    type: 'POTHOLE',
    latitude: 13.0067,
    longitude: 80.2023,
    locationText: 'GST Road, Guindy Flyover Underpass, Chennai',
    roadName: 'GST Road',
    cityId: 'c_chn',
    wardId: 'w-4',
    wardName: 'Ward 4 - Guindy',
    severity: 'HIGH',
    status: 'ACTIVE',
    aiConfidence: 0.82,
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    description: 'Pothole developing under flyover shadow.',
    sourceSummary: 'AI Detection (Fleet)',
    repairStatus: null,
    repairCode: null,
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastObservedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
];

export const DEMO_HAZARD_DETAIL: MunicipalityHazardDetail = {
  ...DEMO_HAZARDS[0],
  citizenReports: [
    {
      id: 'cr-1',
      reportCode: 'RPT-BLR-401',
      hazardType: 'POTHOLE',
      severity: 'CRITICAL',
      description: 'Dangerous deep pothole near IndiranagarHAL junction. Two-wheelers skidding.',
      media: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80'],
      createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    },
  ],
  latestAiAnalysis: {
    id: 'ai-1',
    detected: true,
    confidence: 0.96,
    severity: 'CRITICAL',
    modelVersion: 'SafePath-YOLOv8-v2.1',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  latestFleetObservations: [
    {
      id: 'fo-1',
      vehicleId: 'KA-01-F-1234',
      observedAt: new Date(Date.now() - 1800000).toISOString(),
      observationState: 'CONFIRMED',
      confidence: 0.96,
      severity: 'CRITICAL',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
      latitude: 12.9784,
      longitude: 77.6408,
      dataQuality: 'HIGH',
    },
  ],
  municipalityActions: [
    {
      id: 'act-1',
      actionType: 'ASSIGN_REPAIR',
      notes: 'Assigned to BBMP Road Infrastructure Division with 24h SLA',
      performedBy: 'Officer Rajesh Kumar',
      fromStatus: 'ACTIVE',
      toStatus: 'ACTIVE',
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
  ],
  currentRepair: {
    id: 'rep-301',
    repairCode: 'REP-301',
    status: 'ASSIGNED',
    priority: 'CRITICAL',
    team: 'BBMP Road Infrastructure Division',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
  },
  priority: {
    label: 'CRITICAL',
    score: 96,
    reasons: ['High traffic commercial corridor', 'Deep pothole (>14cm)', 'Multiple fleet detections within 2 hours'],
    recommendation: 'Immediate cold-mix asphalt patch required within 24 hours.',
  },
  resolutionState: 'ACTIVE',
  reopenedFromHazardId: null,
};

export const DEMO_REPAIRS: Repair[] = [
  {
    id: 'rep-301',
    repairCode: 'REP-301',
    hazardId: 'pth-1001',
    hazardRoadName: '100 Feet Road, Indiranagar',
    hazardLocationText: '100 Feet Road, Near HAL 2nd Stage Junction, Indiranagar',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    department: 'BBMP Roads & Bridges',
    zone: 'East Zone',
    team: 'BBMP Road Infrastructure Division',
    assignedOfficerName: 'Officer Rajesh Kumar',
    priority: 'CRITICAL',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
    status: 'ASSIGNED',
    notes: 'Urgent cold-mix patch requested for Ward 101.',
    startedAt: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'rep-302',
    repairCode: 'REP-302',
    hazardId: 'pth-1002',
    hazardRoadName: 'Outer Ring Road',
    hazardLocationText: 'Outer Ring Road, Near Marathahalli Bridge Bus Stop',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    department: 'Highways & Flyovers Dept',
    zone: 'Mahadevapura Zone',
    team: 'L&T Urban Infrastructure Works',
    assignedOfficerName: 'Officer Rajesh Kumar',
    priority: 'CRITICAL',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
    status: 'IN_PROGRESS',
    notes: 'Surface sub-base repair and leveling in progress.',
    startedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'rep-303',
    repairCode: 'REP-303',
    hazardId: 'pth-1003',
    hazardRoadName: '80 Feet Road Koramangala',
    hazardLocationText: '80 Feet Road, 4th Block Koramangala',
    cityId: '59fd1a9b-7f0e-4090-82ea-5372a471af10',
    department: 'BBMP South Division',
    zone: 'South Zone',
    team: 'Rapid Paving Services Ltd',
    assignedOfficerName: 'Officer Rajesh Kumar',
    priority: 'HIGH',
    targetDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: 'READY_FOR_INSPECTION',
    notes: 'Resurfacing completed; awaiting municipal officer sign-off.',
    startedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'rep-201',
    repairCode: 'REP-201',
    hazardId: 'pth-1029',
    hazardRoadName: 'Velachery Main Road',
    hazardLocationText: 'Velachery Main Road, Near Vijaya Nagar Bus Stand',
    cityId: 'c_chn',
    department: 'GCC Roads & Bridges',
    zone: 'South Zone',
    team: 'Chennai Metro Roadways Corp',
    assignedOfficerName: 'Priya Raghavan',
    priority: 'HIGH',
    targetDate: new Date(Date.now() + 86400000).toISOString(),
    status: 'ASSIGNED',
    notes: 'Urgent patch requested by Ward 2 supervisor.',
    startedAt: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
];

export const DEMO_REPAIR_DETAIL: RepairDetail = {
  ...DEMO_REPAIRS[0],
  progressEntries: [
    {
      id: 'prog-1',
      note: 'Site inspection completed. Cold mix material arrived at site.',
      photoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
      latitude: 12.9784,
      longitude: 77.6408,
      createdByName: 'Officer Rajesh Kumar',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  timeline: [
    {
      id: 'tl-1',
      label: 'Repair Created & Assigned',
      detail: 'Assigned to BBMP Road Infrastructure Division',
      fromStatus: null,
      toStatus: 'ASSIGNED',
      actor: 'Officer Rajesh Kumar',
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
  ],
};

export const DEMO_ANALYTICS_SUMMARY: AnalyticsSummary = {
  activeHazards: 42,
  criticalHazards: 8,
  resolvedThisWeek: 34,
  avgResolutionTimeHours: 28.5,
  recurringHazardRoads: 4,
  citizenReportsCount: 86,
  fleetObservationCount: 240,
  avgRepairTurnaroundHours: 24.0,
};
